// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_XxAhC3EvWGGSdnjE9yhFU7ISWGUCDnA',
    appId: '1:450670153488:web:0c9e29b39c42156a649f95',
    messagingSenderId: '450670153488',
    projectId: 'instantgram-naveen',
    authDomain: 'instantgram-naveen.firebaseapp.com',
    storageBucket: 'instantgram-naveen.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo5wFuefnPC41NX_6oOTgyXzzz_OZ2cL8',
    appId: '1:450670153488:android:bb5852eaf6789e8f649f95',
    messagingSenderId: '450670153488',
    projectId: 'instantgram-naveen',
    storageBucket: 'instantgram-naveen.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyhPrURvdfQjQqIGqIKNiTsfrqM78kkiY',
    appId: '1:450670153488:ios:c18e1b3efe50f71a649f95',
    messagingSenderId: '450670153488',
    projectId: 'instantgram-naveen',
    storageBucket: 'instantgram-naveen.appspot.com',
    iosClientId: '450670153488-fqgqeivporm5egosgk88qucrugk0ec5o.apps.googleusercontent.com',
    iosBundleId: 'com.naveenchand.instantgram',
  );
}
